version: "3.9"
services:
  database:
    hostname: database
    image: "postgres:13.2-alpine"
    env_file:
      - database.env
    ports:
      - "5432:5432"
  service:
    build: .
    depends_on:
      - database
    env_file:
      - database.env
      - service.env
    ports:
      - "8080:8080"